#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 8b93847
#
Name     : R-lfe
Version  : 3.1.1
Release  : 70
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/lfe_3.1.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/lfe_3.1.1.tar.gz
Summary  : Linear Group Fixed Effects
Group    : Development/Tools
License  : Apache-2.0
Requires: R-lfe-lib = %{version}-%{release}
Requires: R-Formula
Requires: R-sandwich
Requires: R-xtable
BuildRequires : R-Formula
BuildRequires : R-sandwich
BuildRequires : R-xtable
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Useful for estimating linear models with multiple group fixed effects, and for

%package extras
Summary: extras components for the R-lfe package.
Group: Default

%description extras
extras components for the R-lfe package.


%package lib
Summary: lib components for the R-lfe package.
Group: Libraries

%description lib
lib components for the R-lfe package.


%prep
%setup -q -n lfe
pushd ..
cp -a lfe buildavx2
popd
pushd ..
cp -a lfe buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739374520

%install
export SOURCE_DATE_EPOCH=1739374520
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lfe/CITATION
/usr/lib64/R/library/lfe/DESCRIPTION
/usr/lib64/R/library/lfe/INDEX
/usr/lib64/R/library/lfe/Meta/Rd.rds
/usr/lib64/R/library/lfe/Meta/features.rds
/usr/lib64/R/library/lfe/Meta/hsearch.rds
/usr/lib64/R/library/lfe/Meta/links.rds
/usr/lib64/R/library/lfe/Meta/nsInfo.rds
/usr/lib64/R/library/lfe/Meta/package.rds
/usr/lib64/R/library/lfe/Meta/vignette.rds
/usr/lib64/R/library/lfe/NAMESPACE
/usr/lib64/R/library/lfe/NEWS.Rd
/usr/lib64/R/library/lfe/NEWS.md
/usr/lib64/R/library/lfe/R/lfe
/usr/lib64/R/library/lfe/R/lfe.rdb
/usr/lib64/R/library/lfe/R/lfe.rdx
/usr/lib64/R/library/lfe/TODO
/usr/lib64/R/library/lfe/WORDLIST
/usr/lib64/R/library/lfe/devtools_internal.R
/usr/lib64/R/library/lfe/doc/biascorrection.Rnw
/usr/lib64/R/library/lfe/doc/biascorrection.pdf
/usr/lib64/R/library/lfe/doc/identification.R
/usr/lib64/R/library/lfe/doc/identification.Rnw
/usr/lib64/R/library/lfe/doc/identification.pdf
/usr/lib64/R/library/lfe/doc/index.html
/usr/lib64/R/library/lfe/doc/lfehow.R
/usr/lib64/R/library/lfe/doc/lfehow.Rnw
/usr/lib64/R/library/lfe/doc/lfehow.pdf
/usr/lib64/R/library/lfe/doc/speed.R
/usr/lib64/R/library/lfe/doc/speed.Rnw
/usr/lib64/R/library/lfe/doc/speed.pdf
/usr/lib64/R/library/lfe/help/AnIndex
/usr/lib64/R/library/lfe/help/aliases.rds
/usr/lib64/R/library/lfe/help/figures/README-pressure-1.png
/usr/lib64/R/library/lfe/help/lfe.rdb
/usr/lib64/R/library/lfe/help/lfe.rdx
/usr/lib64/R/library/lfe/help/paths.rds
/usr/lib64/R/library/lfe/html/00Index.html
/usr/lib64/R/library/lfe/html/R.css
/usr/lib64/R/library/lfe/misc/CHANGELOG
/usr/lib64/R/library/lfe/misc/gen2.R
/usr/lib64/R/library/lfe/misc/index.html
/usr/lib64/R/library/lfe/misc/lfeguide.txt
/usr/lib64/R/library/lfe/misc/test2.lfe

%files extras
%defattr(-,root,root,-)
/usr/lib64/R/library/lfe/exec/lfescript

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/lfe/libs/lfe.so
/V4/usr/lib64/R/library/lfe/libs/lfe.so
/usr/lib64/R/library/lfe/libs/lfe.so
